### ISSUE TITLE
Thread Safety : curl_exception's get_traceback's copy is not protected

### ISSUE THREAD

**Issue by vivshankar** [JosephP91/curlcpp#100]
Hi,

There may be a small problem if curlcpp is used from several threads. Since the curl_exception's traceback is a static vector, you will have an issue if the get_traceback function's return value is being copied and an insert happens to the vector that results in the container being reallocated. This will result in a pretty nasty crash because the previous vector element memory is likely invalid now.

For example, say there are 3 elements in traceback. 1 has been copied in get_traceback and then an insert happens from another thread which causes the vector to reallocate. In this case, the 1 element that was copied is going to be invalid memory.

It would be better to provide a new function that takes a vector as an output parameter and use the tracebackLocker to lock the std::copy operation. You can then mark the current function as not thread-safe. Alternatively, can traceback be a non-static member?

**Comment by vivshankar** [comment]
I should add that print_traceback has the same problem in a multi-threaded scenario because an element can be inserted while the iterator is iterating through the vector.

**Comment by JosephP91** [comment]
Hi @vivshankar , yeah, there was a thread safety issue. With the last commit it should be solved.

**Comment by vivshankar** [comment]
Hi Joseph,

Thanks. Unfortunately, this is still not fixed in get_traceback.

  ```
 // Implementation of get_traceback.
    inline curlcpp_traceback curl_exception::get_traceback() const {
        return curl_exception::traceback;
    }
```

When a vector is returned by value, it is making a copy and this copy is not thread-safe. You could resolve this by making an explicit copy inside the function to another vector then return that vector by value. This is only to retain the API that is probably being used by other applications/programs.

So the code looks like this -

 ```
 // Implementation of get_traceback.
    inline curlcpp_traceback curl_exception::get_traceback() const {
       curl_exception::tracebackLocker.lock();
       // Thread-safe copy
       curlcpp_traceback tmp = curl_exception::traceback;
       curl_exception::tracebackLocker.unlock();
       // Returning the tmp vector by value, so it gets copied
        return tmp;
    }

   // New API
   inline void curl_exception::traceback(curlcpp_traceback& traceback) const {
       curl_exception::tracebackLocker.lock();
       // Thread-safe copy
       traceback = curl_exception::traceback;
       curl_exception::tracebackLocker.unlock();
   }
```

**Comment by JosephP91** [comment]
That's right. I'll fix that :)

**Comment by vivshankar** [comment]
Hi Joseph,

The new API avoids two copy operations on the vector. However, that might be an unnecessary optimization, if it's going to be a small vector. 

Regarding the naming, you can call it anything pertinent :-)

**Comment by JosephP91** [comment]
@vivshankar well, that would be a copy constructor, right?

**Comment by vivshankar** [comment]
It could be but won't you need to lock the vector copy operation for a copy constructor too?

**Comment by JosephP91** [comment]
@vivshankar  yes, and If I understand, your API should solve that problem. Right?

**Comment by vivshankar** [comment]
The function below is threadsafe, yes. This isn't making a copy of curl_exception.

```
// New API
  inline void curl_exception::traceback(curlcpp_traceback& traceback) const {
      curl_exception::tracebackLocker.lock();
      // Thread-safe copy
      traceback = curl_exception::traceback;
      curl_exception::tracebackLocker.unlock();
  }
```

A copy constructor will also work and will look like a similar implementation. I don't think you can use the default copy constructor because of the thread-safety issue.

**Comment by JosephP91** [comment]
Sure, I have to implement it. Obviously I cannot use the default one due to the thread-safety issue. I think I will go for the copy constructor implementation solution.

**Comment by vivshankar** [comment]
Sounds good!

**Comment by JosephP91** [comment]
@vivshankar Practically, considering also the implementation of the assignment operator, we will have a situation like this:

```c++

// Thread safe copy constructor .
curl_exception::curl_exception(const curl_exception &object) {
    curl_exception::tracebackLocker.lock();
    curl_exception::traceback = object.get_traceback();
    curl_exception::tracebackLocker.unlock();
}

// Thread safe assignment operator.
curl_exception& curl_exception::operator=(curl_exception &object) {
    curl_exception::tracebackLocker.lock();
    curl_exception::traceback = object.get_traceback();
    curl_exception::tracebackLocker.unlock();
    return *this;
}
```

**Comment by vivshankar** [comment]
Looks great.

**Comment by vivshankar** [comment]
Just a thought. The purpose here is to get the traceback values out and print them out in your application's log files instead of onto stdout using print_traceback. 

get_traceback meets the requirement but with two copy operations for the vector. I think this is fine if the vector is small. Do you anticipate the vector growing very large over time? 

Also, when is the traceback vector cleared? If it never gets cleared and the application makes several requests periodically (like a synchronizing service), it will end up making the vector huge if the server isn't available, for instance, over a few hours. We may need a flush function that could look like the one I proposed earlier -

```
// New API
  inline void curl_exception::flush(curlcpp_traceback& traceback_ref) const {
      curl_exception::tracebackLocker.lock();
      // Thread-safe copy
      traceback_ref = curl_exception::traceback;
      curl_exception::traceback.clear();
      curl_exception::tracebackLocker.unlock();
  }
```

This solves both problems - the ability to get the exception trace in one call and flush the container.

**Comment by JosephP91** [comment]
Yes, it could be useful. I will add it in the next commit. Thank you!

**Comment by vivshankar** [comment]
Thanks!
