### ISSUE TITLE
Homebrew curl?

### ISSUE THREAD

**Issue by Kaned1as** [JosephP91/curlcpp#101]
Homebrew curl installs libs in `/usr/local/opt/curl/libs` by default, not to mess with system-wide libcurl.

Can we add CMake suffix for it as we did with MacPorts?

**Comment by sergey-shambir** [comment]
Is there any example?

**Comment by Adonai** [comment]
I don't remember what dirs Homebrew uses, but for MacPorts relevant lines are these:
```
# Add MacPorts                                                               
if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")                                    
  set(CMAKE_PREFIX_PATH /opt/local ${CMAKE_PREFIX_PATH})                     
endif()       
```

**Comment by JosephP91** [comment]
Now curlcpp is also available via homebrew:

`bash
brew install curlcpp
`
