### ISSUE TITLE
curlcpp releases

### ISSUE THREAD

**Issue by rszibele** [JosephP91/curlcpp#102]
Hi,

could you please add releases to curlcpp? Over at NixOS we packaged curlcpp and it would be great if curlcpp had release tags, so we can properly package and bump the versions of curlcpp in the future.

See my pull request for a version bump over at NixOS/nixpkgs:
https://github.com/NixOS/nixpkgs/pull/25104

**Comment by JosephP91** [comment]
Hi @rszibele 
I am glad to hear that curlcpp is used in NixOS. I have just published the first curlcpp release.

**Comment by rszibele** [comment]
Cheers :beers:.
