### ISSUE TITLE
curl_global should call cleanup in destructor

### ISSUE THREAD

**Issue by sergey-shambir** [JosephP91/curlcpp#103]
CURL uses counter for init/cleanup calls. So calling cleanup from curl_global is safe, but if it doesn't call cleanup, it breaks counter.

**Comment by sergey-shambir** [comment]
I'm going to provide pull request on next weekend.

**Comment by JosephP91** [comment]
Awesome! :)

**Comment by sergey-shambir** [comment]
So it's time to close issue
