### ISSUE TITLE
Problem linking curlcpp in Ubuntu 16.04

### ISSUE THREAD

**Issue by unix121** [JosephP91/curlcpp#109]
Good evening (again),

I would be making this thread unless I had exhausted all my other options.

I've been trying to compile my code in my new Ubuntu 16.04 server but I keep getting the same error every time:

`/usr/lib/ld: cannot find -lcurlcpp`
`collect2: error: ld returned 1 exit status`

Is there any work around for this? (Unfortunately I don't have the option to upgrade my server).
(I've run the installation that you provide without any error)

Thanks in advance,
Stavros

**Comment by JosephP91** [comment]
Hi @unix121 ,
I repeated the entire compile and linking process on an Ubuntu 16.04 virtual machine:

1) Clone the project
2) `cd build && cmake .. && make`
3) Move to the test directory and try to compile the easy example:

`g++ -std=c++11 easy.cpp -L../build/src/ -I../include/ -lcurlcpp -lcurl`

As written in the README.md, you have o add <curlcpp root>/build/src/ to your library path and <curlcpp root>/include/ to your include path, otherwise the library will not be found.

Let me know!

**Comment by unix121** [comment]
Good evening sir,

I've used the library many times in the past so I am familiar with the process, but in that case it still doesn't work.

Keep in mind that I'm using g++-7 instead of normal g++ (forgot to mention it).

**Comment by JosephP91** [comment]
Tried the same commands, but using g++-7:

`g++-7 -std=c++11 easy.cpp -L../build/src/ -I../include/ -lcurlcpp -lcurl`

It compiles. I will do others tests trying to reproduce your error.

**Comment by unix121** [comment]
Well sir, I will keep playing around to see what's wrong. If I find what I did wrong I will reply with the answer in this issue thread. Thank you very much for you help tho.

**Comment by JosephP91** [comment]
No problem! I will do more tests and if I find something I will let you know here. Thank you!

**Comment by unix121** [comment]
I'm sorry to bother you again, but I don't seem to figure it out no matter what.

Could you please tell link me to the exact g++-7 compiler that you used and any other external packages that you have installed as well (if you have installed any). I feel like I'm lost at the moment.

**Comment by JosephP91** [comment]
@unix121 no problem! I have installed g++-7 doing this:

````bash
sudo add-apt-repository ppa:jonathonf/gcc-7.1
sudo apt-get update
sudo apt-get install gcc-7 g++-7
````
And then:

`g++-7 -std=c++11 easy.cpp -L../build/src/ -I../include/ -lcurlcpp -lcurl`

**Comment by unix121** [comment]
@JosephP91 Thank you for the reply, here is exactly what I did and still get the error (I even formatted the server):

`sudo add-apt-repository ppa:jonathonf/gcc-7.1`
`sudo apt-get update`
`sudo apt-get install gcc-7 g++-7`

`git clone https://github.com/josephp91/curlcpp`
`cd curlcpp/build`
`cmake -D CMAKE_CXX_COMPILER="/usr/bin/g++-7" ..`
`make`

and then I tried to execute and example piece of code:

`g++-7 -std=c++17 test.cpp -L../build/src/ -I../include/ -lcurlcpp -lcurl`

but I still get the exact same errors:
`/usr/bin/ld: cannot find -lcurlcpp`
`collect2: error: ld returned 1 exit status`

I know that it's not a problem from your project and it's related to something else, but I'll keep investigating.

**Comment by unix121** [comment]
Quick update:

Solve the problem. I don't know how tho. The only thing that I did differently was change the shell from bash to zsh (which should not effect anything at all , but whatever).

Thanks again for the attention and help.

**Comment by JosephP91** [comment]
@unix121 no problem!
