### ISSUE TITLE
Get response body without response headers

### ISSUE THREAD

**Issue by dbanka** [JosephP91/curlcpp#117]
When I try to get the response body of a http call.. I get this

> HTTP/1.0 200 OK
> Content-Type: text/html; charset=utf-8
> Content-Length: 16
> Server: Werkzeug/0.14.1 Python/2.7.12
> Date: Thu, 05 Jul 2018 06:21:50 GMT
> 
> 0.45390533418869

How do I get the response body only, which in my case is " 0.45390533418869"

**Comment by dbanka** [comment]
Sorry .. it works by default ..I was doing a mistake in my code ..closing this

**Comment by JosephP91** [comment]
No problem ;)
