### ISSUE TITLE
Handle nullptr in versions

### ISSUE THREAD

**Issue by webmaster128** [JosephP91/curlcpp#121]
I just encountered a case where `curl_version_info_data.ssl_version` returns `nullptr`. This leads to a crash (SEGFAULT) when trying to construct a std::string:

![Bildschirmfoto von 2019-03-29 16-30-13](https://user-images.githubusercontent.com/2603011/55246663-f64d6880-5245-11e9-865b-3e0758e0283b.png)

**Comment by JosephP91** [comment]
Errata corrige: in the last commit I wrote 122, but it's 121.
