### ISSUE TITLE
Modern CMake support

### ISSUE THREAD

**Issue by Xeverous** [JosephP91/curlcpp#123]
Hello, I'm interested in using the library however I want to have 2 things: modern C++ and modern CMake. The first one is rather trivial to find info about but the second is (still) rather hard to encounter.

So what I mean by modern CMake is:

- Any project that needs library `foobar` should be enough to just write `target_link_libraries(project_name PRIVATE foobar)`. If there are any compiler/linker flags missing that's the library's fault.
- `foobar` should never touch any global CMake variables  (`CMAKE_*`) as changing any can corrupt the build of the whole dependency tree. It should instead declare everything through `target_*` CMake functions as either `PUBLIC` or `PRIVATE` requirement.

This repository contains rather old CMake recipe, so I'm asking whether you are interested in any PRs. The would bump the minimum required CMake version significantly.

**Comment by JosephP91** [comment]
Hello @Xeverous ,

yes, I am interested in PRs, so If you want you could send one.

**Comment by Xeverous** [comment]
https://github.com/JosephP91/curlcpp/blob/0c2f06df81c6cb24fad11fd12d69a2dd19360285/CMakeLists.txt#L2

Is this line correct? There is no such path in the repository.

**Comment by Xeverous** [comment]
Another thing: do you want to keep the globbing? CMake officially discourages it: https://cmake.org/cmake/help/v3.14/command/file.html. More statements and explanation can be found in [Daniel Pfeifer's modern CMake talk](https://www.youtube.com/watch?v=bsXLMQ6WgIk).

**Comment by JosephP91** [comment]
> https://github.com/JosephP91/curlcpp/blob/0c2f06df81c6cb24fad11fd12d69a2dd19360285/CMakeLists.txt#L2
> 
> Is this line correct? There is no such path in the repository.

You can easly ignore or also remove this line. beecode is an abandoned old project.


> Another thing: do you want to keep the globbing? CMake officially discourages it: https://cmake.org/cmake/help/v3.14/command/file.html. More statements and explanation can be found in [Daniel Pfeifer's modern CMake talk](https://www.youtube.com/watch?v=bsXLMQ6WgIk).

If the globbing is discouraged, feel free to remove it.

**Comment by Xeverous** [comment]
Ok, I will then remove the biicode directory and basically fully rewrite the CMake script. I will also add an option to discover libcurl using pkg-config (off by default), because:

- pkg-config is often the way autotools-based projects report their build and usage requirements. Very common on unix systems and also available for Windows who use Visual or GCC-based toolchain ports such as MinGW-w64
- pkg-config with modern CMake creates very pretty targets (that is, when the `.pc` file is found CMake creates a target that has all include/compiler/linker flags filled and `target_link_libraries(my_project PUBLIC PkgConfig::libname)` is the only required line to make it work)

I will also add these:

- Set default build type to "Release" when none is specified. The default CMake behavior for no build type (no optimization and no debug flags) is not very useful.
- Enable link-time optimization in release build if it is available. Since 3.9 CMake can detect its support automatically.
- Enabling warnings for building curlcpp, but as `PRIVATE` property (so that it is not inherited by descendant projects). Public should be only necessary build and usage requirements but warnings are only a safety feature for the original library maintainers. I have already listed warnings which appeared for me in a separate issue when trying new CMakeLists.txt implementation.

**Comment by Xeverous** [comment]
See #126

**Comment by JosephP91** [comment]
#126 Thank you Xeverous!
