### ISSUE TITLE
compile warning:  invalid use of incomplete type

### ISSUE THREAD

**Issue by weinvest** [JosephP91/curlcpp#128]
from /tmp/curlcpp/test/custom_request.cpp:1:
/tmp/curlcpp/src/../include/curl_pair.h: In member function ‘const curl_httppost* curl::curl_pair<T, curl::curl_form>::second() const’:
/tmp/curlcpp/src/../include/curl_pair.h:157:27: warning: invalid use of incomplete type ‘const class curl::curl_form’
             return (this->value).get();
                    ~~~~~~~^~~~~~
/tmp/curlcpp/src/../include/curl_pair.h:35:11: note: forward declaration of ‘class curl::curl_form’
     class curl_form;
           ^~~~~~~~~
/tmp/curlcpp/src/../include/curl_pair.h: In member function ‘const curl_slist* curl::curl_pair<T, curl::curl_header>::second() const’:
/tmp/curlcpp/src/../include/curl_pair.h:188:27: warning: invalid use of incomplete type ‘const class curl::curl_header’
             return (this->value).get();
                    ~~~~~~~^~~~~~
/tmp/curlcpp/src/../include/curl_pair.h:36:11: note: forward declaration of ‘class curl::curl_header’
     class curl_header;

**Comment by KingDuckZ** [comment]
Getting the same warning with gcc 9.3.0 on gentoo.

**Comment by JosephP91** [comment]
If you look closer `curl_pair` depends on `curl_form` and viceversa. This is a cyclic reference which you can break simply forwarding a declaration of `curl_form` inside `curl_pair`. If you can solve in a better way, you can provide a pull request if you want.
