### ISSUE TITLE
Is a new tag/release coming soon?

### ISSUE THREAD

**Issue by doctor-claw** [JosephP91/curlcpp#141]
I notice it's been a while since the 1.4 release (June 2020) and there have been several useful pull requests merged in since (including the default exclusion of building the examples), is it likely that 1.5 tag will be applied any time soon?

The automated binary dependency management I use builds repo artifacts off tags rather than SHAs, hence the question.

**Comment by JosephP91** [comment]
Hi @doctor-claw , no new releases planned for now
