### ISSUE TITLE
Static build?

### ISSUE THREAD

**Issue by Kaned1as** [JosephP91/curlcpp#148]
I see the project now produces libcurlcpp as a build result.
It was implemented here: https://github.com/JosephP91/curlcpp/commit/e7c7656e4f21e17e6e87cd2f5da17bc491c6566c

Before 2.0 I was using this project also for static builds of curlcpp + libcurl. Are there any plans of bringing it back?

**Comment by JosephP91** [comment]
Hi @Kaned1as I just pushed the fix. Now by default cmake builds the static library. If you want to build the shared/dynamic version, just pass the variable ```-DBUILD_SHARED_LIBS=SHARED``` from command line when you start the build. Let me know if you have problems

**Comment by Kaned1as** [comment]
Thank you, I will have a look today and post back here!

**Comment by JosephP91** [comment]
Great. I also pushed a new version, curlcpp 2.1

**Comment by JosephP91** [comment]
@Kaned1as have you had the chance to test it?

**Comment by Kaned1as** [comment]
@JosephP91 yeah the build works now! But hadn't tested the runtime yet, will continue today

**Comment by JosephP91** [comment]
@Kaned1as ok. Feel free to close the issue if it works. Thanks!
