### ISSUE TITLE
curl_interface is not thread safe

### ISSUE THREAD

**Issue by sarum9in** [JosephP91/curlcpp#19]
According to documentation of curl_global_init(3), this function is not thread safe. It is said that you can't call it in threaded environment. Since curl_interface is inherited by curl_easy and similar classes, they can't be safely used in multithreaded program.

You can check sources of libcurl itself and look onto implementation.
- curl_global_init() uses not-atomic counter `initialized`
- curl_global_init() sets global variables such as Curl_cmalloc declared in lib/curl_memory.h;
  these functions are used everywhere in curl, imagine what could happen if it is partially-set
- it calls various sublibrary initializers such as Curl_ssl_init() which are not safe too, underlying
  SSL library functions can be called from different thread
- etc

You can read mailing lists there
http://curl.haxx.se/mail/lib-2008-02/0116.html
http://curl.haxx.se/mail/lib-2008-02/0124.html
http://curl.haxx.se/mail/lib-2008-02/0126.html

Even usage of mutex is not safe guarantee because some underlying library function can be called without that advisory lock.
But it is probably much better if you document it like "Simultaneous usage of any library libcurl depends on can lead to undefined behavior" and implement lock. It will protect code from double execution of curl_global_init(3) from curl_interface (remember, `initialized` variable inside curl_global_init(3) is not thread safe).
Another option is to break interface of the library and create global initializer object which should be created before usage of the library. It will init curl in constructor and cleanup in destructor.

Here is part of doc about thread safety:
This function is not thread safe. You must not call it when any other thread in the program (i.e. a thread sharing the same memory) is running.  This doesn't just mean no other thread that is using libcurl. Because curl_global_init(3) calls functions of other libraries that are similarly thread unsafe, it could  conflict with any other thread that uses these other libraries.

**Comment by susnux** [comment]
I am also interested in this and want to know if it is fixed?
(I have a multi threaded application where I want to use it, at the moment I work with mutexes (maybe dirty)).

**Comment by sarum9in** [comment]
You can verify that yourself.
https://github.com/JosephP91/curlcpp/blob/master/include/curl_interface.h
is inherited by https://github.com/JosephP91/curlcpp/blob/master/include/curl_easy.h#L853

So it means that for every easy object creation/destruction global_init and global_destroy will be called.
I checked their implementation, they use non-atomic non-locked integer counter + they call non-thread-safe init/destroy functions of underlying SSL library. So it it thread-hostile to use them like in this library, you can't use it from different threads reliably.
