### ISSUE TITLE
Sending JSON data over POST

### ISSUE THREAD

**Issue by edi9999** [JosephP91/curlcpp#22]
Hi, i'm tring to send json data over POST:

Here's my code

```  
curl_easy easy;
curl_header header;
header.add("Content-Type: application/json");
easy.add(curl_pair<CURLoption,curl_header>(CURLOPT_HTTPHEADER, header));
easy.add(curl_pair<CURLoption,string>(CURLOPT_URL, "http://localhost:3000/activePlayers"));
easy.add(curl_pair<CURLoption,string>(CURLOPT_HTTPPOST,a));
try {
    easy.perform();
} catch (curl_easy_exception error) {
    // Print errors, if any
    error.print_traceback();
}
```

I get the following error: 

ERROR: Out of memory ::::: FUNCTION: perform

Any idea how to set the application/json header and send JSON over POST ?

**Comment by JosephP91** [comment]
Hi edie999,
What's the content of "a" variable?

**Comment by edi9999** [comment]
Hi

this is the declaration of a: `string a("[{customer:'Franck'}]");`

**Comment by JosephP91** [comment]
Hi @edi9999 ,
try with this:

```  
curl_form form;
curl_easy easy;

curl_pair<CURLformoption,string> name_form(CURLFORM_COPYNAME,"contant");
curl_pair<CURLformoption,string> name_cont(CURLFORM_COPYCONTENTS,"{[customer:'Franck']}");

try {
   // Form adding
   form.add(name_form,name_cont);
   form.add(pass_form,pass_cont);

   // Add some options to our request
   easy.add(curl_pair<CURLoption,string>(CURLOPT_URL,"http://localhost:3000/activePlayers"));
   easy.add(curl_pair<CURLoption,curl_form>(CURLOPT_HTTPPOST,form));
   easy.perform();
} catch (curl_easy_exception error) {
   // Print errors, if any
   error.print_traceback();
}
```

**Comment by edi9999** [comment]
Hi Joseph, thanks for the help.

It still doesnt work, here is what does work using standard curl in the command line

    curl -i -X POST -H "Content-Type: application/json" -d '[{customer:"Franck"}]'  http://localhost:3000/activePlayers

and here is my current code:



    curl_form form;
    curl_easy easy;

    curl_pair<CURLformoption,string> name_form(CURLFORM_COPYNAME,"content");
    curl_pair<CURLformoption,string> name_cont(CURLFORM_COPYCONTENTS,tables.dump());
    curl_header header;
    header.add("Content-Type: application/json");

    try {
       // Form adding
       form.add(name_form,name_cont);

       // Add some options to our request
       easy.add(curl_pair<CURLoption,curl_header>(CURLOPT_HTTPHEADER, header));
       easy.add(curl_pair<CURLoption,curl_form>(CURLOPT_HTTPPOST,form));
       easy.add(curl_pair<CURLoption,string>(CURLOPT_URL,"http://localhost:3000/activePlayers"));
       easy.perform();
    } catch (curl_easy_exception error) {
       // Print errors, if any
       error.print_traceback();
    }

**Comment by JosephP91** [comment]
Hi @edi9999 ,
Maybe I found another way. I used posttestserver.com to post an example string. I wrote the following code:

``` 
#include "curl_easy.h"
int main()
{
    curl::curl_easy easy; 
    std::string postPayload("[{customer:'Franck'}]");
    
    easy.add(curl_pair<CURLoption,string>(CURLOPT_URL,"http://posttestserver.com/post.php") );
    easy.add(curl_pair<CURLoption, string>(CURLOPT_POSTFIELDS,  "content="+postPayload));
    easy.add(curl_pair<CURLoption, bool>(CURLOPT_POST,  true));
    easy.perform();
    
    return 0;
}
``` 

Can you change the URL with your URL and see if it works? Let me know!

**Comment by edi9999** [comment]
Hi this still doesnt work.

I think the problem is that I need to populate the POST BODY, eg here's the expected result of the post : 

```
Time: Sun, 18 Jan 15 02:54:38 -0800
Source ip: 82.244.34.175

Headers (Some may be inserted by server)
HTTP_CONNECTION = close
REQUEST_URI = /post.php
QUERY_STRING = 
REQUEST_METHOD = POST
GATEWAY_INTERFACE = CGI/1.1
REMOTE_PORT = 56683
REMOTE_ADDR = 82.244.34.175
CONTENT_LENGTH = 21
CONTENT_TYPE = application/json
HTTP_ACCEPT = */*
HTTP_HOST = posttestserver.com
HTTP_USER_AGENT = curl/7.37.1
UNIQUE_ID = VLuQ7tBx6hIAAEzMsZ0AAAAK
REQUEST_TIME_FLOAT = 1421578478.8785
REQUEST_TIME = 1421578478

No Post Params.

== Begin post body ==
[{customer:"Franck"}]
== End post body ==

Upload contains PUT data:
[{customer:"Franck"}]
```

I have created that with curl, with the previous command I put in

**Comment by JosephP91** [comment]
mmm,  @edi9999 try using CURLOPT_POSTFIELDS. It populates che body post.

```
#include "curl_easy.h"
#include "curl_header.h"
int main()
{
    curl::curl_easy easy;
    curl::curl_header header;
    std::string a("[{customer:'Franck'}]");
    header.add("Content-Type: application/json");
    easy.add(curl_pair<CURLoption,curl_header>(CURLOPT_HTTPHEADER, header));
    easy.add(curl_pair<CURLoption,string>(CURLOPT_URL, "http://posttestserver.com/post.php"));
    easy.add(curl_pair<CURLoption,string>(CURLOPT_POSTFIELDS,a));
    try {
        easy.perform();
    } catch (curl_easy_exception error) {
        error.print_traceback();
    }
    return 0;
}
```

The server returns the same content you posted in the previous comment, which is:

Time: Sun, 18 Jan 15 13:17:40 -0800

Headers (Some may be inserted by server)
HTTP_CONNECTION = close
REQUEST_URI = /post.php
QUERY_STRING = 
REQUEST_METHOD = POST
GATEWAY_INTERFACE = CGI/1.1
REMOTE_PORT = 65188
CONTENT_LENGTH = 21
CONTENT_TYPE = application/json
HTTP_ACCEPT = */*
HTTP_HOST = posttestserver.com
UNIQUE_ID = VLwi9NBx6hIAADuQY3cAAAAE
REQUEST_TIME_FLOAT = 1421615860.581
REQUEST_TIME = 1421615860

No Post Params.

== Begin post body ==
[{customer:'Franck'}]
== End post body ==

Upload contains PUT data:
[{customer:'Franck'}]

**Comment by edi9999** [comment]
This works now. Thanks a lot for the help:-)

**Comment by JosephP91** [comment]
Thank you! :)

**Comment by AstralisSomnium** [comment]
This helped me a lot thanks! 

It would be helpful to have this example in the wiki or somewhere.
