### ISSUE TITLE
curl_exception::what()

### ISSUE THREAD

**Issue by qqiangwu** [JosephP91/curlcpp#28]
In curl_exception, we have two `what()` with distinct return type and are selected based on whether the  exception object is constant. This will definitely confuse our user.

eg.

```C++
catch (curl_exception& e) {
    const auto& ce = e;

    std::vector<std::pair<std::string, std::string>> cwhat = ce.what();
    const char* ewhat = e.what();
}
```

This seems nonsence. So why not just rename the new what function as `trace_stack()` or something else?

**Comment by JosephP91** [comment]
Yes, you're right. Renamed to get_traceback(). Thank you!
