### ISSUE TITLE
Use of undeclared identifier when building on OS X 10.10

### ISSUE THREAD

**Issue by naknut** [JosephP91/curlcpp#32]
Im trying to build the project on my OS X 10.10 machine and get the following errors.

```
/curlcpp/src/curl_easy.cpp:6:
include/curl_easy.h:838:31: error: use of undeclared identifier 'CURLOPT_PINNEDPUBLICKEY'
        CURLCPP_DEFINE_OPTION(CURLOPT_PINNEDPUBLICKEY, const char*);

/curlcpp/include/curl_easy.h:841:31: error: use of undeclared identifier 'CURLOPT_UNIX_SOCKET_PATH'
        CURLCPP_DEFINE_OPTION(CURLOPT_UNIX_SOCKET_PATH, const char*);

/curlcpp/include/curl_easy.h:844:31: error: use of undeclared identifier 'CURLOPT_SSL_VERIFYSTATUS'; did you mean 'CURLOPT_SSL_VERIFYHOST'?
        CURLCPP_DEFINE_OPTION(CURLOPT_SSL_VERIFYSTATUS, long);

/curlcpp/include/curl_easy.h:844:9: error: redefinition of 'curl::detail::option_t<CURLOPT_SSL_VERIFYHOST>'
        CURLCPP_DEFINE_OPTION(CURLOPT_SSL_VERIFYSTATUS, long);
```

Do curlcpp not support the OS X version of libcurl?

**Comment by JosephP91** [comment]
The required version is libcurl 7.28 (as written in CMakeLists.txt). I have OSX 10.10 too and I can compile it without errors. What version do you have?

**Comment by naknut** [comment]
Oh, I have 7.37 installed. Will update it and try again.

**Comment by naknut** [comment]
The version that is preinstalled with OS X 10.10 is 7.37.1 and i got the error when i built it with that one. I updated curl with Homebrew to 7.41 and now I can build. As you said, curlcpp says it needs atleast 7.28 but my default version is higher. Maybe the version that comes with OS X be different from the official version?

**Comment by naknut** [comment]
Just so you know I'm not BSing you:

```
naknut@Marcuss-MacBook-Pro:~ $ /usr/bin/curl --version
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz
```
**Can't build with this version**

```
naknut@Marcuss-MacBook-Pro:~ $ curl --version
curl 7.41.0 (x86_64-apple-darwin14.1.0) libcurl/7.41.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
```
**Can build with this version**

**Comment by JosephP91** [comment]
Probably yes. I have installed libcurl downloading it from its website and compiling it. But if it works with your version, it's good.

**Comment by JosephP91** [comment]
@naknut very strange. I will check what are the differences between libcurl OSX version and the on homebrew/port. Are you able to compile now?

**Comment by susnux** [comment]
The problem is the usage of CURLOPT_SSL_VERIFYSTATUS in curl_easy.
It was introduced in 7.41.0
See also here:
http://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYSTATUS.html

> AVAILABILITY
> Added in 7.41.0.
