### ISSUE TITLE
Build Problem in VS2010 / 2013

### ISSUE THREAD

**Issue by patodeborracha** [JosephP91/curlcpp#33]
Hi, Friend!

Whats happening with you Wrapper?

http://codepaste.net/qvja8w

Thank You!

**Comment by JosephP91** [comment]
I read: 'unknown option -std=c++11'. Your c++ version does not support the latest standard! What version do you have?

**Comment by patodeborracha** [comment]
i try compile in vs2010 and vs2013

**Comment by JosephP91** [comment]
And the compiler version is?

**Comment by patodeborracha** [comment]
MSVC++ 12.0 _MSC_VER == 1800 (Visual Studio 2013) I Try this
MSVC++ 11.0 _MSC_VER == 1700 (Visual Studio 2012)
MSVC++ 10.0 _MSC_VER == 1600 (Visual Studio 2010) and this
MSVC++ 9.0  _MSC_VER == 1500 (Visual Studio 2008)
MSVC++ 8.0  _MSC_VER == 1400 (Visual Studio 2005)
MSVC++ 7.1  _MSC_VER == 1310 (Visual Studio 2003)
MSVC++ 7.0  _MSC_VER == 1300
MSVC++ 6.0  _MSC_VER == 1200
MSVC++ 5.0  _MSC_VER == 1100

**Comment by JosephP91** [comment]
And c++11 is supported? You should check if c++11 is supported.

**Comment by JosephP91** [comment]
Or try to enable c++11 compile option, if supported.

**Comment by patodeborracha** [comment]
i'm student, and i'm a noob.. sorry for it...
i see this table: https://msdn.microsoft.com/en-us/library/vstudio/hh567368.aspx
the features of your wrapper is compatible with this?
you have a old version for i build it in VS2010 or VS2013?
thank you!

**Comment by susnux** [comment]
No I do not think it is a compiler problem.
VS2013 should fullfill the requirements, the problem is this line in curlcpp code:

     if (message->easy_handle == easy.get_curl() and message->msg == CURLMSG_DONE) {

the word "and" is, I think, not in the standard and only on gcc available. Try replacing it with "&&".
Please let me know if it works.

**Comment by patodeborracha** [comment]
and to && work fine... thank you!!


1>------ Build started: Project: curlcpp, Configuration: Release Win32 ------
1>cl : Command line warning D9002: ignoring unknown option '-std=c++11'
1>  curl_multi.cpp
1>  curlcpp.vcxproj -> C:\Users\PatodeBorracha\Desktop\curlcpp-master\ProjectVS2013_x86\src\Release\curlcpp.lib
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
