### ISSUE TITLE
Doesn't build on Ubuntu 15.04

### ISSUE THREAD

**Issue by tpoechtrager** [JosephP91/curlcpp#35]
$ LC_ALL=C apt-cache show libcurl4-openssl-dev
    Package: libcurl4-openssl-dev
    Priority: optional
    Section: libdevel
    Installed-Size: 1232
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Original-Maintainer: Alessandro Ghedini <ghedo@debian.org>
    Architecture: amd64
    Source: curl
    Version: 7.38.0-3ubuntu2
    Provides: libcurl-dev, libcurl-ssl-dev, libcurl3-dev, libcurl3-openssl-dev, libcurl4-dev
    Depends: libcurl3 (= 7.38.0-3ubuntu2)
    Suggests: libcurl4-doc, libcurl3-dbg, libidn11-dev, libkrb5-dev, libldap2-dev, librtmp-dev, libssl-dev, pkg-config, zlib1g-dev
    Conflicts: libcurl4-gnutls-dev, libcurl4-nss-dev
    Filename: pool/main/c/curl/libcurl4-openssl-dev_7.38.0-3ubuntu2_amd64.deb
    Size: 252648
    MD5sum: 776693e739d63610ed5699f922477c11
    SHA1: 6bd217c3cc0363f2acbca72838001130ef102a00
    SHA256: c743a29acad89eee05351b47a6d50b10b59a8a42ad3ce1fae8e05999c2e57a93
    Description-en: development files and documentation for libcurl (OpenSSL flavour)
    [...]
    Description-md5: 9ef3e0d3a9a6f50f79b0deaff858c410
    Multi-Arch: same
    Homepage: http://curl.haxx.se
    Bugs: https://bugs.launchpad.net/ubuntu/+filebug
    Origin: Ubuntu
    Supported: 9m

    $ cmake .. -DCMAKE_BUILD_TYPE=Release -DWITHOUT_OCSP_STAPLING=1
    -- The C compiler identification is Clang 3.6.1
    -- The CXX compiler identification is Clang 3.6.1
    -- Check for working C compiler: /opt/compiler/llvm-3.6/bin/clang
    -- Check for working C compiler: /opt/compiler/llvm-3.6/bin/clang -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /opt/compiler/llvm-3.6/bin/clang++
    -- Check for working CXX compiler: /opt/compiler/llvm-3.6/bin/clang++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found suitable version "7.38.0", minimum required is "7.28.0")
    CMake Warning (dev) at CMakeLists.txt:34 (get_property):
      Policy CMP0026 is not set: Disallow use of the LOCATION target property.
      Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.

      The LOCATION property should not be read from target "curlcpp".  Use the
      target name directly with add_custom_command, or use the generator
      expression $<TARGET_FILE>, as appropriate.

    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/thomas/development/ipgrep/curlcpp/build

    $ make VERBOSE=1
    /usr/bin/cmake -H/home/thomas/development/ipgrep/curlcpp -B/home/thomas/development/ipgrep/curlcpp/build --check-build-system CMakeFiles/Makefile.cmake 0
    /usr/bin/cmake -E cmake_progress_start /home/thomas/development/ipgrep/curlcpp/build/CMakeFiles /home/thomas/development/ipgrep/curlcpp/build/CMakeFiles/progress.marks
    make -f CMakeFiles/Makefile2 all
    make[1]: Entering directory '/data/development/ipgrep/curlcpp/build'
    make -f src/CMakeFiles/curlcpp.dir/build.make src/CMakeFiles/curlcpp.dir/depend
    make[2]: Entering directory '/data/development/ipgrep/curlcpp/build'
    cd /home/thomas/development/ipgrep/curlcpp/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/thomas/development/ipgrep/curlcpp /home/thomas/development/ipgrep/curlcpp/src /home/thomas/development/ipgrep/curlcpp/build /home/thomas/development/ipgrep/curlcpp/build/src /home/thomas/development/ipgrep/curlcpp/build/src/CMakeFiles/curlcpp.dir/DependInfo.cmake --color=
    make[2]: Leaving directory '/data/development/ipgrep/curlcpp/build'
    make -f src/CMakeFiles/curlcpp.dir/build.make src/CMakeFiles/curlcpp.dir/build
    make[2]: Entering directory '/data/development/ipgrep/curlcpp/build'
    /usr/bin/cmake -E cmake_progress_report /home/thomas/development/ipgrep/curlcpp/build/CMakeFiles 1
    [ 12%] Building CXX object src/CMakeFiles/curlcpp.dir/curl_easy.cpp.o
    cd /home/thomas/development/ipgrep/curlcpp/build/src && /opt/compiler/llvm-3.6/bin/clang++   -DWITHOUT_OCSP_STAPLING -std=c++11 -O3 -DNDEBUG -I/home/thomas/development/ipgrep/curlcpp/include    -o CMakeFiles/curlcpp.dir/curl_easy.cpp.o -c /home/thomas/development/ipgrep/curlcpp/src/curl_easy.cpp
    In file included from /home/thomas/development/ipgrep/curlcpp/src/curl_easy.cpp:6:
    /home/thomas/development/ipgrep/curlcpp/include/curl_easy.h:838:31: error: use of undeclared identifier 'CURLOPT_PINNEDPUBLICKEY'
            CURLCPP_DEFINE_OPTION(CURLOPT_PINNEDPUBLICKEY, const char*);
                                  ^
    /home/thomas/development/ipgrep/curlcpp/include/curl_easy.h:47:33: note: expanded from macro 'CURLCPP_DEFINE_OPTION'
        template <> struct option_t<opt> {\
                                    ^
    /home/thomas/development/ipgrep/curlcpp/include/curl_easy.h:841:31: error: use of undeclared identifier 'CURLOPT_UNIX_SOCKET_PATH'
            CURLCPP_DEFINE_OPTION(CURLOPT_UNIX_SOCKET_PATH, const char*);
                                  ^
    /home/thomas/development/ipgrep/curlcpp/include/curl_easy.h:47:33: note: expanded from macro 'CURLCPP_DEFINE_OPTION'
        template <> struct option_t<opt> {\
                                    ^
    2 errors generated.
    src/CMakeFiles/curlcpp.dir/build.make:54: recipe for target 'src/CMakeFiles/curlcpp.dir/curl_easy.cpp.o' failed
    make[2]: *** [src/CMakeFiles/curlcpp.dir/curl_easy.cpp.o] Error 1
    make[2]: Leaving directory '/data/development/ipgrep/curlcpp/build'
    CMakeFiles/Makefile2:75: recipe for target 'src/CMakeFiles/curlcpp.dir/all' failed
    make[1]: *** [src/CMakeFiles/curlcpp.dir/all] Error 2
    make[1]: Leaving directory '/data/development/ipgrep/curlcpp/build'
    Makefile:76: recipe for target 'all' failed
    make: *** [all] Error 2

The same happens with `g++` too. I am using the latest sources as of writing.

**Comment by JosephP91** [comment]
@tpoechtrager I created an Ubuntu 15.04 virtual machine to reproduce your development environment and errors. Checking on libcurl website, I see that many of the not found constants, like CURLOPT_PINNEDPUBLICKEY, has been added in libcurl 7.41, while Ubuntu has libcurl 7.38 installed. Downloading libcurl 7.41, compiling it and installing it, has solved the problem and I have been able to compile curlcpp.

**Comment by tpoechtrager** [comment]
Upgrading isn't always the best solution. Why don't you `#ifdef` them out?
Also this seems to be related to https://github.com/JosephP91/curlcpp/issues/32.

**Comment by susnux** [comment]
I think handling this like #32 would be a good idea, anyway CURLOPT_PINNEDPUBLICKEY was added in 7.39 ;-)

**Comment by JosephP91** [comment]
@susnux right, in the 7.39. My mistake :)

**Comment by susnux** [comment]
I committed a fix for this bug. However this will only will bring backwards compatibility until 7.38.
If this should work with all curl version back to 7.28 there are few more macros which have to put in `#if` `#endif`. So @JosephP91 should it be backwards compatible? I think it is not much more work.

**Comment by JosephP91** [comment]
Mmm, yes, it should be!
