### ISSUE TITLE
__declspec(dllexport/dllimport)

### ISSUE THREAD

**Issue by patodeborracha** [JosephP91/curlcpp#36]
I try Compile Your Code After Solve and to &&., now have this issue:
http://pastie.org/10096159

I found in google, and it solve this problem for static lib..
but i not know where i define this declspec!

http://pastie.org/10096171

**Comment by susnux** [comment]
It looks like you have an old compiled version (old object files), can you try a clean version?

**Comment by patodeborracha** [comment]
i build a last version of github... i not use compiled versions!

**Comment by patodeborracha** [comment]
not work for me...
i'll use libcurl without wrappers in my Project..
thank you!

**Comment by susnux** [comment]
Do you really think this is fixed? I could not reproduce it but I do not know the configuration of the thread starter.

PS the && problem is fixed in upstream so you can try it without your fix.

**Comment by patodeborracha** [comment]
now this work... i link libcurl in my Project... sorry for it! i'm noob!
i think not need link libcurl because i think it is embeded in wrapper!!
sorry again!
