### ISSUE TITLE
Compiling under Fedora 20/libcurl 7.32.0 doesn not work

### ISSUE THREAD

**Issue by rubdos** [JosephP91/curlcpp#50]
```
/home/rsmet/src/sf.net/githubpp/curlcpp/include/curl_easy.h:280:31: error: ‘CURLOPT_DEPRECATED72’ was not declared in this scope
         CURLCPP_DEFINE_OPTION(CURLOPT_DEPRECATED72, long);
                               ^
/home/rsmet/src/sf.net/githubpp/curlcpp/include/curl_easy.h:47:33: note: in definition of macro ‘CURLCPP_DEFINE_OPTION’
     template <> struct option_t<opt> {\
                                 ^
/home/rsmet/src/sf.net/githubpp/curlcpp/include/curl_easy.h:47:36: error: template argument 1 is invalid
     template <> struct option_t<opt> {\
                                    ^
/home/rsmet/src/sf.net/githubpp/curlcpp/include/curl_easy.h:280:9: note: in expansion of macro ‘CURLCPP_DEFINE_OPTION’
         CURLCPP_DEFINE_OPTION(CURLOPT_DEPRECATED72, long);
```

Apparently, the ` #if defined(LIBCURL_VERSION_NUM) && LIBCURL_VERSION_NUM > 0x072500 ` block fails, but commenting out so it will define the CURLOPT_OBSOLETE72 doesn't work either. 

Any clue? I first tried as a submodule, but compiling it like in the README gives the same error.

**Comment by dkleissa** [comment]
I'm having the same issue on OSX 10.9.5

**Comment by JosephP91** [comment]
Mmm, I'm trying to figure it out. @susnux can I ask your opinion? Any clue?

**Comment by susnux** [comment]
Yes there was a mistake, it is called OBSOLETE72 in 37.1 and later.
Before it is called CLOSEPOLICY (this option was never implemented in cURL and never had any effect).

**Comment by JosephP91** [comment]
@dkleissa can you check if this commit solved your issue? Thank you!

**Comment by rubdos** [comment]
For me this solves the issue. Thank you :)

**Comment by JosephP91** [comment]
@rubdos Good. If @dkleissa was having the same issue, I suppose the commit definitely solved it. So you can close it.
