### ISSUE TITLE
Example of sending a form doesn't work

### ISSUE THREAD

**Issue by czaarek99** [JosephP91/curlcpp#64]
Im pretty new to C++ and I am using this library. But the example with the form does not compile because you can not easy.add a form for object.

**Comment by JosephP91** [comment]
Hi @czaarek99 ,
I have fixed the readme examples! Can you try now (also updating your local copy) and let me now? Thank you!

**Comment by czaarek99** [comment]
I don't know if I don't understand something due to learning C++ but is it intended to have to use a const_cast to be able to pass the curl_httppost? Because I get the error that it is a const pointer and can't do it.
`easy.add<CURLOPT_HTTPPOST>(const_cast<curl_httppost*>(form.get()));`

**Comment by JosephP91** [comment]
@czaarek99 you don't need to use a const_cast. Why are you using it?

**Comment by czaarek99** [comment]
Otherwise my IDE complains with this:
http://puu.sh/mhbIP.png
And it won't compile.

**Comment by JosephP91** [comment]
@czaarek99 Got it. I'm pushing a fix right now. Let me know!

**Comment by czaarek99** [comment]
Thank you, works just fine now :+1:

**Comment by JosephP91** [comment]
Good! Thank you!
