### ISSUE TITLE
alternative from C callback function to c++11 lambdas?

### ISSUE THREAD

**Issue by kangjoni76** [JosephP91/curlcpp#65]
Because of CURLOPT_PROGRESSFUNCTION require interoperability to c++ using static member function, that is very costly for multithread code. Declaring private instance member data class doesn't compile even on VS2015 on windows. I m still thinking how to solve this, but that seems would be too much reinvent the wheel and losing much libcurl event system. I know here the root cause problem is on it's libcurl callback and need some ideas..

**Comment by JosephP91** [comment]
Well, while we think about it, I will clos the issue, since it is not a bug, but a could be a pull request one day.
