### ISSUE TITLE
Fixes #44 was withdrawn in the commit on Oct 14, 2015

### ISSUE THREAD

**Issue by scytulip** [JosephP91/curlcpp#74]
As a result, the issues #44 still remains.... Not compatible to libcurl < 7.35.1.

**Comment by susnux** [comment]
You mean this?

https://github.com/JosephP91/curlcpp/commit/ca71ff519bb625bec7840980fdd187c5408f3372#diff-f148623625dde67998c67766529322d7L275

**Comment by scytulip** [comment]
Yes
