### ISSUE TITLE
getinfo for curl_easy interface

### ISSUE THREAD

**Issue by typedeph** [JosephP91/curlcpp#78]
Perhaps I miss something while searching the source but is there a way to use getinfo (https://curl.haxx.se/libcurl/c/curl_easy_getinfo.html) from the curl easy interface? I am particularly trying to get the status code of a request after calling perform.

**Comment by JosephP91** [comment]
@typedeph  I will put a get_info method in the next commit. Thank you!

**Comment by JosephP91** [comment]
@typedeph I just pushed a commit with get_info method for curl_easy interface. You will find an example in the README.md and in tests/easy_info.cpp. Let me know if everything works.

**Comment by typedeph** [comment]
I just went from:
`      long code;
      curl_easy_getinfo(easy.get_curl(), CURLINFO_RESPONSE_CODE, &code);`
to:
`      long code = easy.get_info<long>(CURLINFO_RESPONSE_CODE).get().second;`

Will probably split it along two lines for better readibility. Thanks, great job with the wrapper.

**Comment by JosephP91** [comment]
@typedeph you're right. The bug should be fixed with the last commit. Do a git pull and let me know! You can remove the part where you obtain the pair object. Pair has been removed. You will get just the variable containing the code you are trying to print.

**Comment by JosephP91** [comment]
It should be fixed now.

**Comment by typedeph** [comment]
Sorry for the late response, I was not able to get on my Linux machine until now. I did want to confirm that it is fixed though.

**Comment by JosephP91** [comment]
Good! Thank you!

**Comment by ronny332** [comment]
Hi,

may be I do something wrong, but with the latest version from github a usage of

`auto code = easy.get_info<long>(CURLINFO_RESPONSE_CODE);`

ends in

`error: no matching function for call to ‘curl::curl_easy::get_info(CURLINFO)’`

Were there any changes, which make the usage of get_info impossible?

**Comment by JosephP91** [comment]
Good @ronny332
