### ISSUE TITLE
Exception after setting CURLOPT_HTTP_VERSION to CURL_HTTP_VERSION_2_0

### ISSUE THREAD

**Issue by osanwe** [JosephP91/curlcpp#84]
Hello!

I tried to built the first example, and it works well. Next I tried to add http2 support to it:
```cpp
easy.add<CURLOPT_HTTP_VERSION>(3);
```
and after that I got the follow error:
```
terminate called after throwing an instance of 'curl::curl_easy_exception'
  what():  std::exception
Aborted (core dumped)
```

```
~> curl -V
curl 7.49.0 (x86_64-pc-linux-gnu) libcurl/7.49.0 OpenSSL/1.0.2h zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Comment by JosephP91** [comment]
Hi @osanwe 
Well, I noticed that, if you put the easy.add<CURLOPT_HTTP_VERSION>(3); inside a try-catch block, the error is: Unsupported protocol. 
P.s.: you can use CURL_HTTP_VERSION_2_0 (or CURL_HTTP_VERSION_2), if you want, instead of 3.

**Comment by osanwe** [comment]
@JosephP91 
Well, thanks!
Is there a way to use http2 without rebuilding libcurl? Unfortunately Mer SDK hasn't cURL with http2.

**Comment by JosephP91** [comment]
I really don't know, but you could try asking this question in the libcurl mailing list or contacting libcurl creator. Let me know!

**Comment by JosephP91** [comment]
Since this is not a bug of curlcpp library, I will close the issue.
