### ISSUE TITLE
Issue in README.md with curl::curl_easy::get_info();

### ISSUE THREAD

**Issue by tkaden4** [JosephP91/curlcpp#86]
In the examples given in the readme, it indicates that to retrieve the content-type from a curl::curl::easy request, you must do this: 

// Retrieve information about curl current session.
auto x = easy.get_info\<char>(CURLINFO_CONTENT_TYPE);
// Print content type
std::cout << x.get().second << std::endl;

while in reality, the correct way to do this was

// Retrieve information about curl current session.
auto x = easy.get_info\<CURL_CONTENT_TYPE>();
// Print out content type
std::cout << x.get() << std::endl;

**Comment by JosephP91** [comment]
Example fixed. Thank you @tkaden4

**Comment by tkaden4** [comment]
No problem.
