### ISSUE TITLE
accidental crash

### ISSUE THREAD

**Issue by JacobMao** [JosephP91/curlcpp#88]
I am using curlcpp in my iOS app, and sometimes it happens crash.
<img width="863" alt="screen shot 2016-07-21 at 10 43 49 am" src="https://cloud.githubusercontent.com/assets/5173117/17009705/09c4c7a8-4f30-11e6-808e-7e9573212de0.png">

**Comment by JacobMao** [comment]
another attachment
<img width="1229" alt="screen shot 2016-07-21 at 10 44 31 am" src="https://cloud.githubusercontent.com/assets/5173117/17016925/e19a458a-4f63-11e6-8241-40288909dbdb.png">

**Comment by JosephP91** [comment]
hi @JacobMao !
can you report your piece of code? Without knowing how you are using curlcpp's perform() function, I really don't know how to help-

**Comment by JacobMao** [comment]
ok.

my piece of code:
try {
    easy.perform();
} catch (curl_easy_exception error) {
}

these codes are inside a member function of class, and I create instance of the class in various multithreading.

**Comment by JosephP91** [comment]
@JacobMao without the entire piece of code I can't help you. I can not reproduce the problem. Does xCode reports you a null pointer? What is happening?

**Comment by JacobMao** [comment]
I found this function in curl_exception.cpp file:
`curl_exception::curl_exception(const std::string &error, const std::string &fun_name) {   curl_exception::traceback.insert(curl_exception::traceback.begin(),curlcpp_traceback_object(error,fun_name));
}`

because traceback is a static member variable of curl_exception,  Is it threadsafe that use function of insert in multithreading environment?

**Comment by JacobMao** [comment]
@JosephP91 hello?

**Comment by JosephP91** [comment]
Hi @JacobMao, sorry for the delay in the response. Yes, it couls be, since curlcpp is not thread safe yet. I have accepted your pull request. Is the problem solved? Let me know!
