### ISSUE TITLE
curl_multi should not be copyable

### ISSUE THREAD

**Issue by ilyapopov** [JosephP91/curlcpp#89]
Currently, curl_multi provides a copy constructor and a copy assignment operator. 

The [copy constructor](https://github.com/JosephP91/curlcpp/blob/master/src/curl_multi.cpp#L30) actually creates a completely independent new multi handle but assigns `message_queued` and `active_count`, which does not make sense at all. 

The [assignment operator](https://github.com/JosephP91/curlcpp/blob/master/src/curl_multi.cpp#L41) just initializes the new multi handle.

I believe that the  copy constructor and assignment operators should be deleted (`= delete`), 
and move constructor and move assignment provided instead if necessary.
### Update

Similarly, I think that `curl_easy` should not be copyable by default either. Otherwise it is too easy to copy accidentally (for example, when storing a `curl_easy` in a container). Instead, there should be a `.clone()` method for the case there the user wants to clone the handle.
### Update2

Actually, this issues can be easily solved by wrapping the handle into a `std::unique_ptr` like this:

``` c++
class curl_multi
{
    struct deleter
    {
        void operator()(CURLM* h) const
        {
            curl_multi_cleanup(h);
        }
    };

    std::unique_ptr<CURLM, deleter> handle_;

    // other members here...
}
```

This will automatically provide safe moving and prohibit copying and automatically provide a destructor.

**Comment by amerlyq** [comment]
Why functor? Why not directly `std::unique_ptr<CURLM, curl_multi_cleanup> handle_;` ? Any reasons I can't catch up with?

**Comment by ilyapopov** [comment]
Second argument of unique_ptr must be a type. It can be a function pointer type, like this:

    unique_ptr<CURLM, void(*)(CURLM*)> handle_;

But then you have to provide concrete pointer at the construction:

    curl_multi::curl_multi()
        : handle_(nullptr, curl_multi_cleanup)
    {}

This way, the function pointer would be stored in the pointer object itself, unnecessarily taking space. With the functor, the call is resolved at compile time, and no additional space of time is spent.
