### ISSUE TITLE
curl_easy_info<char*>::get when value is NULL

### ISSUE THREAD

**Issue by hatkirby** [JosephP91/curlcpp#93]
`curl_easy::get_info` returns a `curl_easy_info`, which usually makes its value available via `curl_easy_info::get`, but for `char*` types the template specialization converts the value to an `std::string`. This causes an exception (with an unhelpful error message) to be raised if the info value was null.

Specific example: I've been encountering an issue with `CURLINFO_CONTENT_TYPE`. The documentation for `CURLINFO_CONTENT_TYPE` states that its value can be null if "the server didn't send a valid Content-Type header or that the protocol used doesn't support this." I've been encountering issues where the following code raises an exception because of this:

`auto content_type = handle.get_info<CURLINFO_CONTENT_TYPE>().get();`

It'd be nice to be able to at least check before calling `get` that the info value wasn't null, because currently there is no way to know as far as I can tell.

**Comment by JosephP91** [comment]
That's right @hatkirby 

````c++
template<> class curl_easy_info<char *> {
    public:
        curl_easy_info(char *pointer) : _pointer(pointer) {}
        std::string get() const {
            return std::string(_pointer);
        }
    private:
        char *_pointer;
    };
````

This is the template specialization of `curl_easy_info` for a `char *` response. I will put a control before `return std::string(pointer);`.

**Comment by JosephP91** [comment]
@hatkirby any news?

**Comment by hatkirby** [comment]
Works for me!

**Comment by JosephP91** [comment]
Good. I will close the issue. Thank you!
