### ISSUE TITLE
Uploading via CURLFORM_BUFFER

### ISSUE THREAD

**Issue by Adonai** [JosephP91/curlcpp#96]
I added one more overloaded `add` function, to use it like this:

    std::vector<char> data;
    ...
    nameForm.add(curl_pair<CURLformoption, string>(CURLFORM_COPYNAME, "file"),
                 curl_pair<CURLformoption, string>(CURLFORM_BUFFER, "1.txt"),
                 curl_pair<CURLformoption, char*>(CURLFORM_BUFFERPTR, &data[0]),
                 curl_pair<CURLformoption, long>(CURLFORM_BUFFERLENGTH, static_cast<long>(data.size())));

I'm ready to upstream this, would you accept such PR?

**Comment by JosephP91** [comment]
@Adonai sure!

**Comment by JosephP91** [comment]
Merged. I will close the issue. Thank you!
