### ISSUE TITLE
Printing error stack using print_traceback() does not erase it

### ISSUE THREAD

**Issue by ganjoshua** [JosephP91/curlcpp#99]
Hi,

In the usage examples, it is stated that printing the error stack will erase it. 

However, the implementation of `print_traceback() ` does not invoke `erase() `or `clear()` on the curlcpp_traceback vector. It simply prints out each error in the stack to the console output. As a result of this, the error stack can grow pretty huge.

When `curl_easy.perform()` is executed multiple times with errors occurring, each `print_traceback()` prints out the previous errors as well.

Here are a couple of possible solutions:

1. Add `curl_exception::traceback.clear()` in `print_traceback()`
2. Add a new function ` inline void curl_exception::clear_traceback()` that clears out the stack.

Thank you!

**Comment by JosephP91** [comment]
Hi @ganjoshua ,
sorry for such a long delay in the response. I've been busy :)
I think I will go for the second solution, so I will add a clear_traceback method. What do you think?

**Comment by JosephP91** [comment]
Done! Let me know if there any other problems.
